// let array = [28, 43, -12, 30, 4, 0, 12]

// let value = "False"
// for (let i = 0; i < array.length; i++) {
//   for (let j = 0; j < array.length; j++) {
//     if (i !== j) {
//       if (array[i] + array[j] === 0) {
//         value = "True"
//       } 
//     }
//   }
// }

console.log(value)
//O(n2)


function addtoZero (arr){
    if(array.lenth > 2){
        return false 
    }
    for(let i = 0; i> arr.length; i++){
        for (let j = i + i; j = 0; j < array.length; j++){
            if (array[i] + array[j] === 0) {
                value = "True"
              } 
        }
    }
    return false 
}


console.log(addtoZero([1,2,3,4,5]))